config/routes.rb
Rails.application.routes.draw do
  
  root "billboards#index"

  resources :billboards do 
  resources :artist
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
end

app/models/billboard.rb
class Billboard < ApplicationRecord
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :billboard
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def new
  end
end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  
  before_action :set_billboard, except: [:index, :new, :create]
  
  def index
    @billboards = Billboard.all
  end

  def show
    #before_action - set_billboard
  end
  
  def edit
    #before_action - set_billboard
  end
  
  def update
    if @billboard.update(billboard_params)
      redirect_to billboard_path
    else
      render :edit
    end
  end

  def new
    @billboard = Billboard.new
  end

  def create
    @billboard = Billboard.new(billboard_params)
    if @billboard.save
      redirect_to billboards_path
    else
      render :new
    end
  end

  def destroy
    @billboard.destroy
    redirect_to billboard_path
  end

    private

    def billboard_params
      params.require(:billboard).permit(:name, :location)
    end
    
    def set_billboard
      @billboard = Billboard.find(params[:id])
    end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<h1>Artists#index</h1>
<p>Find me in app/views/artists/index.html.erb</p>

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/artists/show.html.erb
<h1>Artists#show</h1>
<p>Find me in app/views/artists/show.html.erb</p>

app/views/billboards/edit.html.erb
<h1>Billboards#edit</h1>
<p>Find me in app/views/billboards/edit.html.erb</p>

app/views/billboards/index.html.erb
<h1>Click a Billboard Top Artists/Song to View!</h1>
<%= link_to "Add a New Billboard", new_billboard_path %>
<ul>
<% @billboards.each do |billboard| %>
  <li>
    <%= link_to billboard.name, billboard %>
  </li>
</ul>
  <br />
  <br />
  <br />
  <%= link_to "Let Me See this Billboard!", billboard_path(billboard) %>
  <br />
  <br />
  <br />
  <%= link_to "Get Rid of this Billboard!", billboard_path(billboard), method: :destroy %>
  <br />
  <br />
  <br />
<% end %>

app/views/billboards/new.html.erb
<h1>Create a New Billboard</h1>
<%= form_for @billboard do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  
  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.submit %>
  <% end %>
  

app/views/billboards/show.html.erb
<h1><%= @billboard.name %></h1>
<hr />
<p>What would you like to do?</p>
  <br />
  <%= link_to "Edit this Billboard", edit_billboard_path(@billboard) %>
  <br />
  <%= link_to "Delete this Billboard", @billboard, method: :delete %>
  <br />
  <%= link_to "Go back to Billboards", billboard_path %>
  <br />
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Top100</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <div class="ui container" >
    <%= yield %>
    </div>
  </body>
</html>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/index.html.erb
<h1>Songs#index</h1>
<p>Find me in app/views/songs/index.html.erb</p>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/show.html.erb
<h1>Songs#show</h1>
<p>Find me in app/views/songs/show.html.erb</p>